import 'package:flutter/material.dart';
import '../../core/app_controller.dart';
import '../broadcasts/broadcast_page.dart';
import '../commands/commands_page.dart';
import '../dashboard/dashboard_page.dart';
import '../more/more_page.dart';
import '../scheduled/scheduled_page.dart';

class HomeShell extends StatefulWidget{const HomeShell({super.key,required this.controller});final AppController controller;@override State<HomeShell> createState()=>_HomeShellState();}
class _HomeShellState extends State<HomeShell>{int _index=0;static const _destinations=[NavigationDestination(icon:Icon(Icons.home_rounded),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.quickreply_rounded),label:'الردود'),NavigationDestination(icon:Icon(Icons.schedule_send_rounded),label:'المجدولة'),NavigationDestination(icon:Icon(Icons.campaign_rounded),label:'إرسال'),NavigationDestination(icon:Icon(Icons.grid_view_rounded),label:'المزيد')];List<Widget> _pages()=>[DashboardPage(controller:widget.controller),CommandsPage(controller:widget.controller),ScheduledPage(controller:widget.controller),BroadcastPage(controller:widget.controller),MorePage(controller:widget.controller)];@override Widget build(BuildContext context)=>ListenableBuilder(listenable:widget.controller,builder:(context,_){final pages=_pages();return LayoutBuilder(builder:(context,constraints){final wide=constraints.maxWidth>=820;final body=IndexedStack(index:_index,children:pages);if(wide)return Scaffold(body:SafeArea(child:Row(children:[NavigationRail(selectedIndex:_index,onDestinationSelected:(v)=>setState(()=>_index=v),labelType:NavigationRailLabelType.all,destinations:_destinations.map((d)=>NavigationRailDestination(icon:d.icon,selectedIcon:d.selectedIcon,label:Text(d.label))).toList()),const VerticalDivider(width:1),Expanded(child:body)])));return Scaffold(body:SafeArea(child:body),bottomNavigationBar:NavigationBar(selectedIndex:_index,onDestinationSelected:(v)=>setState(()=>_index=v),destinations:_destinations,labelBehavior:NavigationDestinationLabelBehavior.onlyShowSelected));});});}
