import 'dart:async';
import 'package:flutter/material.dart';
import '../../core/app_controller.dart';
import '../../core/models.dart';
import '../messaging/content_composer.dart';
import '../messaging/group_selector.dart';

class BroadcastPage extends StatefulWidget{const BroadcastPage({super.key,required this.controller});final AppController controller;@override State<BroadcastPage> createState()=>_BroadcastPageState();}
class _BroadcastPageState extends State<BroadcastPage>{
  @override Widget build(BuildContext context){final items=widget.controller.broadcasts.where((e)=>e.kind=='manual').toList();return Scaffold(backgroundColor:Colors.transparent,appBar:AppBar(title:const Text('إرسال للمجموعات'),backgroundColor:Colors.transparent,actions:[IconButton(onPressed:widget.controller.refreshBroadcasts,icon:const Icon(Icons.refresh_rounded))]),floatingActionButton:FloatingActionButton.extended(onPressed:_compose,icon:const Icon(Icons.campaign_rounded),label:const Text('إرسال جديد')),body:RefreshIndicator(onRefresh:widget.controller.refreshBroadcasts,child:items.isEmpty?ListView(padding:const EdgeInsets.all(24),children:const[SizedBox(height:110),Icon(Icons.campaign_outlined,size:64),SizedBox(height:18),Text('لا يوجد سجل إرسال جماعي بعد.',textAlign:TextAlign.center),SizedBox(height:8),Text('أنشئ رسالة، اختر جميع المجموعات أو مجموعات محددة، راجعها ثم أرسل.',textAlign:TextAlign.center)]):ListView.separated(padding:const EdgeInsets.fromLTRB(16,8,16,90),itemCount:items.length,separatorBuilder:(_,_)=>const SizedBox(height:10),itemBuilder:(context,index){final e=items[index];return Card(child:ListTile(onTap:()=>_openReport(e.id),leading:CircleAvatar(child:Icon(_statusIcon(e.status))),title:Text('إرسال #${e.id}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${_statusLabel(e.status)} • ${e.sentCount}/${e.targetCount} نجح${e.failedCount>0?' • ${e.failedCount} فشل':''}\n${e.content.summary}',maxLines:3,overflow:TextOverflow.ellipsis)));})));}
  Future<void> _compose()async{final d=await Navigator.push<ApiBroadcast>(context,MaterialPageRoute(builder:(_)=>BroadcastWizardPage(controller:widget.controller)));if(d!=null){await widget.controller.refreshBroadcasts();if(mounted)await _openReport(d.id);}}
  Future<void> _openReport(int id)async{await Navigator.push<void>(context,MaterialPageRoute(builder:(_)=>BroadcastReportPage(controller:widget.controller,broadcastId:id)));await widget.controller.refreshBroadcasts();}
}

class BroadcastWizardPage extends StatefulWidget{const BroadcastWizardPage({super.key,required this.controller});final AppController controller;@override State<BroadcastWizardPage> createState()=>_BroadcastWizardPageState();}
class _BroadcastWizardPageState extends State<BroadcastWizardPage>{ApiMessageContent _content=const ApiMessageContent(components:[]);String _targetMode='all';Set<int> _groupIds={};int _step=0;bool _sending=false;
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('إرسال جديد للمجموعات')),body:Stepper(currentStep:_step,onStepTapped:(v)=>setState(()=>_step=v),onStepContinue:_sending?null:_continue,onStepCancel:_sending||_step==0?null:()=>setState(()=>_step--),controlsBuilder:(context,d)=>Padding(padding:const EdgeInsets.only(top:18),child:Row(children:[FilledButton.icon(onPressed:d.onStepContinue,icon:Icon(_step==2?Icons.send_rounded:Icons.arrow_forward_rounded),label:Text(_step==2?'إرسال الآن':'التالي')),if(_step>0)...[const SizedBox(width:8),TextButton(onPressed:d.onStepCancel,child:const Text('السابق'))]])),steps:[Step(title:const Text('1. المحتوى'),isActive:_step>=0,content:ContentComposer(controller:widget.controller,value:_content,onChanged:(v)=>setState(()=>_content=v),title:'الرسالة التي ستصل للمجموعات')),Step(title:const Text('2. المستهدفون'),isActive:_step>=1,content:GroupSelector(groups:widget.controller.groups,mode:_targetMode,selectedIds:_groupIds,onModeChanged:(v)=>setState((){_targetMode=v;if(v=='all')_groupIds.clear();}),onSelectionChanged:(v)=>setState(()=>_groupIds=v))),Step(title:const Text('3. المراجعة والإرسال'),isActive:_step>=2,content:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[ListTile(contentPadding:EdgeInsets.zero,title:const Text('المستهدفون'),trailing:Text(_targetMode=='all'?'جميع المجموعات المعتمدة':'${_groupIds.length} مجموعة',style:const TextStyle(fontWeight:FontWeight.bold))),const SizedBox(height:8),const Text('المحتوى',style:TextStyle(fontWeight:FontWeight.bold)),Card(child:Padding(padding:const EdgeInsets.all(14),child:Text(_content.summary))),const SizedBox(height:10),const Card(child:Padding(padding:EdgeInsets.all(14),child:Text('سيتم الإرسال للمجموعات بشكل متسلسل عبر طابور الإرسال، وستظهر نتيجة كل مجموعة في التقرير.'))),if(_sending)const Padding(padding:EdgeInsets.only(top:12),child:LinearProgressIndicator())]))]));
  Future<void> _continue()async{if(_step==0&&_content.isEmpty)return _msg('أضف محتوى الرسالة أولًا.');if(_step==1&&_targetMode=='selected'&&_groupIds.isEmpty)return _msg('اختر مجموعة واحدة على الأقل.');if(_step<2){setState(()=>_step++);return;}setState(()=>_sending=true);try{final d=await widget.controller.api.createBroadcast(content:_content,targetMode:_targetMode,groupIds:_groupIds.toList());if(mounted)Navigator.pop(context,d);}catch(e){_msg('تعذر بدء الإرسال: $e');}finally{if(mounted)setState(()=>_sending=false);}}void _msg(String t){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));}
}

class BroadcastReportPage extends StatefulWidget{const BroadcastReportPage({super.key,required this.controller,required this.broadcastId});final AppController controller;final int broadcastId;@override State<BroadcastReportPage> createState()=>_BroadcastReportPageState();}
class _BroadcastReportPageState extends State<BroadcastReportPage>{ApiBroadcast? _item;Timer? _timer;bool _loading=true;@override void initState(){super.initState();_load();_timer=Timer.periodic(const Duration(seconds:2),(_){final s=_item?.status;if(s=='queued'||s=='running')_load(silent:true);});}@override void dispose(){_timer?.cancel();super.dispose();}Future<void> _load({bool silent=false})async{if(!silent&&mounted)setState(()=>_loading=true);try{_item=await widget.controller.api.getBroadcast(widget.broadcastId);}catch(e){if(mounted&&!silent)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر تحميل التقرير: $e')));}finally{if(mounted)setState(()=>_loading=false);}}
  @override Widget build(BuildContext context){final e=_item;return Scaffold(appBar:AppBar(title:Text('تقرير الإرسال #${widget.broadcastId}'),actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh_rounded))]),body:_loading&&e==null?const Center(child:CircularProgressIndicator()):e==null?const Center(child:Text('تعذر العثور على الإرسال.')):ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[Icon(_statusIcon(e.status),size:48),const SizedBox(height:8),Text(_statusLabel(e.status),style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:14),Row(children:[Expanded(child:_metric('المستهدفون',e.targetCount)),Expanded(child:_metric('تم',e.sentCount)),Expanded(child:_metric('فشل',e.failedCount))]),if(e.status=='queued'||e.status=='running')...[const SizedBox(height:14),LinearProgressIndicator(value:e.targetCount==0?null:(e.sentCount+e.failedCount)/e.targetCount)]]))),const SizedBox(height:12),const Text('الرسالة',style:TextStyle(fontWeight:FontWeight.bold)),Card(child:Padding(padding:const EdgeInsets.all(14),child:Text(e.content.summary))),if(e.targets.isNotEmpty)...[const SizedBox(height:16),Text('نتائج المجموعات',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),...e.targets.map((t)=>Card(child:ListTile(leading:Icon(_statusIcon(t.status)),title:Text(t.groupName),subtitle:Text('${_statusLabel(t.status)} • المحاولات: ${t.attemptCount}${t.lastError==null?'':'\n${t.lastError}'}'))))],const SizedBox(height:16),if(e.retryable)FilledButton.tonalIcon(onPressed:_retry,icon:const Icon(Icons.refresh_rounded),label:const Text('إعادة محاولة الفاشل فقط')),if(e.cancellable)...[const SizedBox(height:8),OutlinedButton.icon(onPressed:_cancel,icon:const Icon(Icons.cancel_outlined),label:const Text('إلغاء ما لم يُرسل بعد'))]]));}
  Widget _metric(String l,int v)=>Column(children:[Text('$v',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),Text(l)]);Future<void> _retry()async{await widget.controller.api.retryBroadcast(widget.broadcastId);await _load();}Future<void> _cancel()async{await widget.controller.api.cancelBroadcast(widget.broadcastId);await _load();}
}
IconData _statusIcon(String s)=>switch(s){'completed'||'sent'=>Icons.check_circle_rounded,'failed'=>Icons.error_rounded,'cancelled'=>Icons.cancel_rounded,'running'||'sending'=>Icons.sync_rounded,'queued'||'pending'=>Icons.schedule_rounded,_=>Icons.info_outline_rounded};String _statusLabel(String s)=>switch(s){'completed'=>'مكتمل','sent'=>'تم الإرسال','failed'=>'فشل','cancelled'=>'ملغي','running'||'sending'=>'جاري الإرسال','queued'=>'في الطابور','pending'=>'بانتظار الإرسال',_=>s};
