class ApiMediaAsset {
  const ApiMediaAsset({required this.id, required this.kind, required this.mimeType, required this.sizeBytes, required this.originalName, required this.createdAt});
  final int id; final String kind; final String mimeType; final int sizeBytes; final String? originalName; final int createdAt;
  factory ApiMediaAsset.fromJson(Map<String,dynamic> json)=>ApiMediaAsset(id:_int(json['id']),kind:'${json['kind']??''}',mimeType:'${json['mimeType']??''}',sizeBytes:_int(json['sizeBytes']),originalName:json['originalName']?.toString(),createdAt:_int(json['createdAt']));
}

class ApiContentComponent {
  const ApiContentComponent({required this.type,this.text,this.assetId,this.caption,this.asset});
  final String type; final String? text; final int? assetId; final String? caption; final ApiMediaAsset? asset;
  bool get isText=>type=='text';
  factory ApiContentComponent.fromJson(Map<String,dynamic> json)=>ApiContentComponent(type:'${json['type']??''}',text:json['text']?.toString(),assetId:json['assetId']==null?null:_int(json['assetId']),caption:json['caption']?.toString(),asset:json['asset'] is Map?ApiMediaAsset.fromJson(Map<String,dynamic>.from(json['asset'] as Map)):null);
  Map<String,dynamic> toJson()=>type=='text'?{'type':'text','text':text??''}:{'type':type,'assetId':assetId,if(caption!=null&&caption!.trim().isNotEmpty)'caption':caption};
  ApiContentComponent copyWith({String? caption})=>ApiContentComponent(type:type,text:text,assetId:assetId,caption:caption??this.caption,asset:asset);
}

class ApiMessageContent {
  const ApiMessageContent({required this.components}); final List<ApiContentComponent> components;
  bool get isEmpty=>components.isEmpty; bool get isNotEmpty=>components.isNotEmpty;
  factory ApiMessageContent.fromJson(Map<String,dynamic>? json)=>ApiMessageContent(components:json==null?[]:((json['components'] as List?)??const[]).whereType<Map>().map((e)=>ApiContentComponent.fromJson(Map<String,dynamic>.from(e))).toList());
  Map<String,dynamic> toJson()=>{'version':1,'components':components.map((e)=>e.toJson()).toList()};
  String get summary { if(components.isEmpty)return 'لا يوجد محتوى'; return components.map((e)=>switch(e.type){'text'=>e.text??'','image'=>e.caption?.trim().isNotEmpty==true?'🖼️ صورة — ${e.caption}':'🖼️ صورة','video'=>e.caption?.trim().isNotEmpty==true?'🎬 فيديو — ${e.caption}':'🎬 فيديو','voice'=>e.caption?.trim().isNotEmpty==true?'🎙️ رسالة صوتية — ${e.caption}':'🎙️ رسالة صوتية','audio'=>e.caption?.trim().isNotEmpty==true?'🎵 صوت — ${e.caption}':'🎵 صوت',_=>e.type}).join('\n'); }
}

class ApiCommand {
  ApiCommand({required this.id,required this.title,required this.enabled,required this.responseText,required this.responseContent,required this.cooldownSeconds,required this.usageCount,required this.triggers,required this.scopes,required this.scopeMode,required this.groupIds});
  final int id; final String title; final bool enabled; final String responseText; final ApiMessageContent responseContent; final int cooldownSeconds; final int usageCount; final List<ApiTrigger> triggers; final List<String> scopes; final String scopeMode; final List<int> groupIds;
  factory ApiCommand.fromJson(Map<String,dynamic> json){ final c=ApiMessageContent.fromJson(json['responseContent'] is Map?Map<String,dynamic>.from(json['responseContent'] as Map):null); final legacy='${json['responseText']??''}'; return ApiCommand(id:_int(json['id']),title:'${json['title']??''}',enabled:json['enabled']==true,responseText:legacy,responseContent:c.isNotEmpty?c:ApiMessageContent(components:legacy.trim().isEmpty?[]:[ApiContentComponent(type:'text',text:legacy)]),cooldownSeconds:_int(json['cooldownSeconds']),usageCount:_int(json['usageCount']),triggers:((json['triggers'] as List?)??const[]).whereType<Map>().map((e)=>ApiTrigger.fromJson(Map<String,dynamic>.from(e))).toList(),scopes:((json['scopes'] as List?)??const[]).map((e)=>'$e').toList(),scopeMode:'${json['scopeMode']??(((json['scopes'] as List?)?.contains('global')==true)?'all':'selected')}',groupIds:((json['groupIds'] as List?)??const[]).map(_int).toList()); }
}
class ApiTrigger { ApiTrigger({required this.id,required this.text,required this.primary}); final int id; final String text; final bool primary; factory ApiTrigger.fromJson(Map<String,dynamic> j)=>ApiTrigger(id:_int(j['id']),text:'${j['text']??''}',primary:j['primary']==true); }
class ApiGroup { ApiGroup({required this.id,required this.name,required this.status,required this.responsesEnabled,required this.memberCount}); final int id; final String name; final String status; final bool responsesEnabled; final int? memberCount; bool get approved=>status=='approved'; factory ApiGroup.fromJson(Map<String,dynamic> j)=>ApiGroup(id:_int(j['id']),name:'${j['name']??'مجموعة بدون اسم'}',status:'${j['status']??''}',responsesEnabled:j['responsesEnabled']==true,memberCount:j['memberCount']==null?null:_int(j['memberCount'])); }

class ApiScheduledMessage { const ApiScheduledMessage({required this.id,required this.text,required this.content,required this.sortOrder,required this.timesSent,required this.lastSentAt}); final int id; final String text; final ApiMessageContent content; final int sortOrder; final int timesSent; final int? lastSentAt; factory ApiScheduledMessage.fromJson(Map<String,dynamic> j)=>ApiScheduledMessage(id:_int(j['id']),text:'${j['text']??''}',content:ApiMessageContent.fromJson(j['content'] is Map?Map<String,dynamic>.from(j['content'] as Map):null),sortOrder:_int(j['sortOrder']),timesSent:_int(j['timesSent']),lastSentAt:j['lastSentAt']==null?null:_int(j['lastSentAt'])); }
class ApiScheduledTarget { const ApiScheduledTarget({required this.groupId,required this.groupName,required this.status}); final int groupId; final String groupName; final String status; factory ApiScheduledTarget.fromJson(Map<String,dynamic> j)=>ApiScheduledTarget(groupId:_int(j['groupId']),groupName:'${j['groupName']??'مجموعة'}',status:'${j['status']??''}'); }
class ApiScheduledCampaign { const ApiScheduledCampaign({required this.id,required this.name,required this.enabled,required this.intervalSeconds,required this.selectionMode,required this.targetMode,required this.lastSentAt,required this.nextRunAt,required this.messages,required this.targets}); final int id; final String name; final bool enabled; final int intervalSeconds; final String selectionMode; final String targetMode; final int? lastSentAt; final int? nextRunAt; final List<ApiScheduledMessage> messages; final List<ApiScheduledTarget> targets; List<int> get groupIds=>targets.map((e)=>e.groupId).toList(); factory ApiScheduledCampaign.fromJson(Map<String,dynamic> j)=>ApiScheduledCampaign(id:_int(j['id']),name:'${j['name']??''}',enabled:j['enabled']==true,intervalSeconds:_int(j['intervalSeconds']),selectionMode:'${j['selectionMode']??'shuffle'}',targetMode:'${j['targetMode']??'all'}',lastSentAt:j['lastSentAt']==null?null:_int(j['lastSentAt']),nextRunAt:j['nextRunAt']==null?null:_int(j['nextRunAt']),messages:((j['messages'] as List?)??const[]).whereType<Map>().map((e)=>ApiScheduledMessage.fromJson(Map<String,dynamic>.from(e))).toList(),targets:((j['targets'] as List?)??const[]).whereType<Map>().map((e)=>ApiScheduledTarget.fromJson(Map<String,dynamic>.from(e))).toList()); }

class ApiOutboundTarget { const ApiOutboundTarget({required this.groupId,required this.groupName,required this.status,required this.attemptCount,required this.lastError,required this.sentAt}); final int groupId; final String groupName; final String status; final int attemptCount; final String? lastError; final int? sentAt; factory ApiOutboundTarget.fromJson(Map<String,dynamic> j)=>ApiOutboundTarget(groupId:_int(j['groupId']),groupName:'${j['groupName']??'مجموعة'}',status:'${j['status']??''}',attemptCount:_int(j['attemptCount']),lastError:j['lastError']?.toString(),sentAt:j['sentAt']==null?null:_int(j['sentAt'])); }
class ApiBroadcast { const ApiBroadcast({required this.id,required this.kind,required this.messageText,required this.content,required this.targetMode,required this.status,required this.targetCount,required this.sentCount,required this.failedCount,required this.createdAt,required this.startedAt,required this.finishedAt,required this.targets}); final int id; final String kind; final String messageText; final ApiMessageContent content; final String targetMode; final String status; final int targetCount; final int sentCount; final int failedCount; final int? createdAt; final int? startedAt; final int? finishedAt; final List<ApiOutboundTarget> targets; bool get retryable=>failedCount>0; bool get cancellable=>status=='queued'||status=='running'; factory ApiBroadcast.fromJson(Map<String,dynamic> j)=>ApiBroadcast(id:_int(j['id']),kind:'${j['kind']??''}',messageText:'${j['messageText']??''}',content:ApiMessageContent.fromJson(j['content'] is Map?Map<String,dynamic>.from(j['content'] as Map):null),targetMode:'${j['targetMode']??'all'}',status:'${j['status']??''}',targetCount:_int(j['targetCount']),sentCount:_int(j['sentCount']),failedCount:_int(j['failedCount']),createdAt:j['createdAt']==null?null:_int(j['createdAt']),startedAt:j['startedAt']==null?null:_int(j['startedAt']),finishedAt:j['finishedAt']==null?null:_int(j['finishedAt']),targets:((j['targets'] as List?)??const[]).whereType<Map>().map((e)=>ApiOutboundTarget.fromJson(Map<String,dynamic>.from(e))).toList()); }

class ApiApproval { ApiApproval({required this.id,required this.groupName,required this.memberCount,required this.actorName,required this.actorPhone,required this.expiresAt}); final int id; final String groupName; final int? memberCount; final String? actorName; final String? actorPhone; final int expiresAt; factory ApiApproval.fromJson(Map<String,dynamic> j)=>ApiApproval(id:_int(j['id']),groupName:'${j['groupName']??'مجموعة'}',memberCount:j['memberCount']==null?null:_int(j['memberCount']),actorName:j['actorName']?.toString(),actorPhone:j['actorPhone']?.toString(),expiresAt:_int(j['expiresAt'])); }
class ApiUsageRank { const ApiUsageRank({required this.id,required this.title,required this.uses}); final int id; final String title; final int uses; factory ApiUsageRank.fromJson(Map<String,dynamic> j)=>ApiUsageRank(id:_int(j['id']),title:'${j['title']??''}',uses:_int(j['uses'])); }
class ApiStatistics { const ApiStatistics({required this.total,required this.top,required this.approvedGroups,required this.commands}); final int total; final List<ApiUsageRank> top; final int approvedGroups; final int commands; factory ApiStatistics.fromJson(Map<String,dynamic> j)=>ApiStatistics(total:_int(j['total']),top:((j['top'] as List?)??const[]).whereType<Map>().map((e)=>ApiUsageRank.fromJson(Map<String,dynamic>.from(e))).toList(),approvedGroups:_int(j['approvedGroups']),commands:_int(j['commands'])); static const empty=ApiStatistics(total:0,top:[],approvedGroups:0,commands:0); }
class ApiWhatsAppStatus { const ApiWhatsAppStatus({required this.state,required this.registered,required this.usableSession,required this.requiresRelink,required this.pairingReady,required this.lastError}); final String state; final bool registered; final bool usableSession; final bool requiresRelink; final bool pairingReady; final String? lastError; bool get connected=>state=='ready'&&usableSession; bool get connecting=>state=='connecting'||state=='disconnected'; factory ApiWhatsAppStatus.fromJson(Map<String,dynamic> j)=>ApiWhatsAppStatus(state:'${j['state']??''}',registered:j['registered']==true,usableSession:j['usableSession']==true,requiresRelink:j['requiresRelink']==true,pairingReady:j['pairingReady']==true,lastError:j['lastError']?.toString()); static const empty=ApiWhatsAppStatus(state:'',registered:false,usableSession:false,requiresRelink:false,pairingReady:false,lastError:null); }
class EnrollmentResult { EnrollmentResult({required this.id,required this.enrollmentToken,required this.verificationCode,required this.status,required this.expiresAt}); final String id; final String enrollmentToken; final String verificationCode; final String status; final int expiresAt; factory EnrollmentResult.fromJson(Map<String,dynamic> j)=>EnrollmentResult(id:'${j['id']}',enrollmentToken:'${j['enrollmentToken']}',verificationCode:'${j['verificationCode']}',status:'${j['status']}',expiresAt:_int(j['expiresAt'])); }
class SessionTokens { SessionTokens({required this.accessToken,required this.refreshToken,required this.accessExpiresAt,required this.refreshExpiresAt}); final String accessToken; final String refreshToken; final int accessExpiresAt; final int refreshExpiresAt; factory SessionTokens.fromJson(Map<String,dynamic> j)=>SessionTokens(accessToken:'${j['accessToken']}',refreshToken:'${j['refreshToken']}',accessExpiresAt:_int(j['accessExpiresAt']),refreshExpiresAt:_int(j['refreshExpiresAt'])); }
int _int(Object? value)=>value is num?value.toInt():int.tryParse('$value')??0;
