import 'package:flutter/material.dart';
import '../../core/app_controller.dart';
import '../../core/models.dart';
import '../messaging/content_composer.dart';
import '../messaging/group_selector.dart';

class ScheduledPage extends StatefulWidget{const ScheduledPage({super.key,required this.controller});final AppController controller;@override State<ScheduledPage> createState()=>_ScheduledPageState();}
class _ScheduledPageState extends State<ScheduledPage>{
  @override Widget build(BuildContext context){final items=widget.controller.scheduledCampaigns;return Scaffold(backgroundColor:Colors.transparent,appBar:AppBar(title:const Text('الرسائل المجدولة'),backgroundColor:Colors.transparent,actions:[IconButton(onPressed:widget.controller.refreshScheduled,icon:const Icon(Icons.refresh_rounded))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_openWizard(),icon:const Icon(Icons.add_alarm_rounded),label:const Text('جدول جديد')),body:RefreshIndicator(onRefresh:widget.controller.refreshScheduled,child:items.isEmpty?ListView(padding:const EdgeInsets.all(24),children:const[SizedBox(height:100),Icon(Icons.schedule_send_rounded,size:64),SizedBox(height:18),Text('لا توجد رسائل مجدولة بعد.',textAlign:TextAlign.center),SizedBox(height:8),Text('أنشئ جدولًا، اختر المجموعات، أضف مجموعة رسائل، ثم فعّل الجدولة.',textAlign:TextAlign.center)]):ListView.separated(padding:const EdgeInsets.fromLTRB(16,8,16,90),itemCount:items.length,separatorBuilder:(_,_)=>const SizedBox(height:10),itemBuilder:(context,index){final c=items[index];return Card(child:ListTile(onTap:()=>_openDetails(c),leading:CircleAvatar(child:Icon(c.enabled?Icons.schedule_send_rounded:Icons.pause_rounded)),title:Text(c.name,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${_intervalLabel(c.intervalSeconds)} • ${_selectionLabel(c.selectionMode)}\n${c.messages.length} رسالة • ${c.targetMode=='all'?'كل المجموعات':'${c.targets.length} مجموعة'}'),trailing:Switch(value:c.enabled,onChanged:(v)async{await widget.controller.api.updateScheduledCampaign(c.id,{'enabled':v});await widget.controller.refreshScheduled();})));})));}
  Future<void> _openWizard([ApiScheduledCampaign? c])async{final changed=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>ScheduledWizardPage(controller:widget.controller,campaign:c)));if(changed==true)await widget.controller.refreshScheduled();}
  Future<void> _openDetails(ApiScheduledCampaign c)async{final changed=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>ScheduledDetailsPage(controller:widget.controller,campaignId:c.id)));if(changed==true)await widget.controller.refreshScheduled();}
}

class ScheduledWizardPage extends StatefulWidget{const ScheduledWizardPage({super.key,required this.controller,this.campaign});final AppController controller;final ApiScheduledCampaign? campaign;@override State<ScheduledWizardPage> createState()=>_ScheduledWizardPageState();}
class _ScheduledWizardPageState extends State<ScheduledWizardPage>{
  late final TextEditingController _name,_hours;late String _selectionMode,_targetMode;late Set<int> _groupIds;late bool _enabled;ApiMessageContent _initial=const ApiMessageContent(components:[]);int _step=0;bool _saving=false;bool get editing=>widget.campaign!=null;
  @override void initState(){super.initState();final c=widget.campaign;_name=TextEditingController(text:c?.name??'');_hours=TextEditingController(text:c==null?'12':_hoursText(c.intervalSeconds));_selectionMode=c?.selectionMode??'shuffle';_targetMode=c?.targetMode??'all';_groupIds={...?c?.groupIds};_enabled=c?.enabled??false;}
  @override void dispose(){_name.dispose();_hours.dispose();super.dispose();}
  @override Widget build(BuildContext context){final last=editing?3:4;return Scaffold(appBar:AppBar(title:Text(editing?'تعديل الجدول':'إنشاء جدول رسائل')),body:Stepper(currentStep:_step,onStepTapped:(v)=>setState(()=>_step=v),onStepContinue:_saving?null:_continue,onStepCancel:_saving||_step==0?null:()=>setState(()=>_step--),controlsBuilder:(context,d)=>Padding(padding:const EdgeInsets.only(top:18),child:Row(children:[FilledButton.icon(onPressed:d.onStepContinue,icon:Icon(_step==last?Icons.save_rounded:Icons.arrow_forward_rounded),label:Text(_step==last?(editing?'حفظ الجدول':'إنشاء الجدول'):'التالي')),if(_step>0)...[const SizedBox(width:8),TextButton(onPressed:d.onStepCancel,child:const Text('السابق'))]])),steps:[
    Step(title:const Text('1. الاسم والتكرار'),isActive:_step>=0,content:Column(children:[TextField(controller:_name,maxLength:120,decoration:const InputDecoration(labelText:'اسم الجدول',hintText:'مثال: تذكيرات عامة')),const SizedBox(height:10),TextField(controller:_hours,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'التكرار بالساعات',helperText:'مثال: 12 = كل 12 ساعة. الحد الأدنى 5 دقائق (0.083 ساعة).'))])),
    Step(title:const Text('2. المجموعات'),isActive:_step>=1,content:GroupSelector(groups:widget.controller.groups,mode:_targetMode,selectedIds:_groupIds,onModeChanged:(v)=>setState((){_targetMode=v;if(v=='all')_groupIds.clear();}),onSelectionChanged:(v)=>setState(()=>_groupIds=v))),
    Step(title:const Text('3. طريقة الاختيار والتفعيل'),isActive:_step>=2,content:Column(children:[RadioListTile<String>(value:'shuffle',groupValue:_selectionMode,title:const Text('عشوائي بدون تكرار'),subtitle:const Text('يرسل كل الرسائل مرة قبل بدء دورة جديدة.'),onChanged:(v)=>setState(()=>_selectionMode=v!)),RadioListTile<String>(value:'random',groupValue:_selectionMode,title:const Text('عشوائي بالكامل'),onChanged:(v)=>setState(()=>_selectionMode=v!)),RadioListTile<String>(value:'ordered',groupValue:_selectionMode,title:const Text('بالترتيب'),onChanged:(v)=>setState(()=>_selectionMode=v!)),SwitchListTile(contentPadding:EdgeInsets.zero,value:_enabled,title:const Text('تفعيل الجدول بعد الحفظ'),subtitle:const Text('يمكنك تركه متوقفًا حتى تنتهي من إضافة الرسائل.'),onChanged:(v)=>setState(()=>_enabled=v))])),
    if(!editing)Step(title:const Text('4. أول رسالة'),isActive:_step>=3,content:ContentComposer(controller:widget.controller,value:_initial,onChanged:(v)=>_initial=v,title:'أول رسالة في مجموعة الجدول')),
    Step(title:Text('${editing?4:5}. المراجعة والحفظ'),isActive:_step>=last,content:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_review('الاسم',_name.text.trim()),_review('التكرار',_intervalLabel(_seconds()??0)),_review('الاختيار',_selectionLabel(_selectionMode)),_review('المجموعات',_targetMode=='all'?'جميع المجموعات المعتمدة':'${_groupIds.length} مجموعة محددة'),_review('الحالة',_enabled?'مفعّل':'متوقف'),if(!editing)...[const SizedBox(height:10),const Text('أول رسالة',style:TextStyle(fontWeight:FontWeight.bold)),Card(child:Padding(padding:const EdgeInsets.all(14),child:Text(_initial.summary)))],if(_saving)const Padding(padding:EdgeInsets.only(top:16),child:LinearProgressIndicator())]))
  ]));}
  Widget _review(String t,String v)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(t),trailing:Flexible(child:Text(v,textAlign:TextAlign.end,style:const TextStyle(fontWeight:FontWeight.bold))));
  Future<void> _continue()async{final last=editing?3:4;if(_step==0){if(_name.text.trim().isEmpty)return _msg('اكتب اسم الجدول.');final s=_seconds();if(s==null||s<300||s>31536000)return _msg('أدخل تكرارًا صحيحًا من 5 دقائق حتى سنة.');}if(_step==1&&_targetMode=='selected'&&_groupIds.isEmpty)return _msg('اختر مجموعة واحدة على الأقل.');if(!editing&&_step==3&&_initial.isEmpty)return _msg('أضف أول رسالة للجدول.');if(_step<last){setState(()=>_step++);return;}await _save();}
  Future<void> _save()async{setState(()=>_saving=true);try{final s=_seconds()!;if(editing){await widget.controller.api.updateScheduledCampaign(widget.campaign!.id,{'name':_name.text.trim(),'intervalSeconds':s,'selectionMode':_selectionMode,'targetMode':_targetMode,'groupIds':_targetMode=='all'?<int>[]:_groupIds.toList(),'enabled':_enabled});}else{final c=await widget.controller.api.createScheduledCampaign(name:_name.text.trim(),intervalSeconds:s,selectionMode:_selectionMode,targetMode:_targetMode,groupIds:_groupIds.toList(),enabled:_enabled);await widget.controller.api.addScheduledMessage(c.id,_initial);}if(mounted)Navigator.pop(context,true);}catch(e){_msg('تعذر حفظ الجدول: $e');}finally{if(mounted)setState(()=>_saving=false);}}
  int? _seconds(){final h=double.tryParse(_hours.text.trim().replaceAll(',','.'));return h==null||h<=0?null:(h*3600).round();}void _msg(String t){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));}
}

class ScheduledDetailsPage extends StatefulWidget{const ScheduledDetailsPage({super.key,required this.controller,required this.campaignId});final AppController controller;final int campaignId;@override State<ScheduledDetailsPage> createState()=>_ScheduledDetailsPageState();}
class _ScheduledDetailsPageState extends State<ScheduledDetailsPage>{ApiScheduledCampaign? _campaign;bool _busy=true;@override void initState(){super.initState();_load();}Future<void> _load()async{setState(()=>_busy=true);try{_campaign=ApiScheduledCampaign.fromJson(await widget.controller.api.getMap('/scheduled-campaigns/${widget.campaignId}'));}finally{if(mounted)setState(()=>_busy=false);}}
  @override Widget build(BuildContext context){final c=_campaign;return Scaffold(appBar:AppBar(title:Text(c?.name??'الجدول'),actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh_rounded))]),body:_busy||c==null?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[SwitchListTile(contentPadding:EdgeInsets.zero,value:c.enabled,title:const Text('التشغيل'),subtitle:Text(c.enabled?'الجدول يعمل':'الجدول متوقف'),onChanged:(v)async{await widget.controller.api.updateScheduledCampaign(c.id,{'enabled':v});await _load();}),const Divider(),_info('التكرار',_intervalLabel(c.intervalSeconds)),_info('طريقة الاختيار',_selectionLabel(c.selectionMode)),_info('النطاق',c.targetMode=='all'?'جميع المجموعات المعتمدة':'${c.targets.length} مجموعة'),_info('الإرسال القادم',_date(c.nextRunAt)),_info('آخر إرسال',_date(c.lastSentAt))]))),const SizedBox(height:12),Row(children:[Expanded(child:FilledButton.icon(onPressed:c.messages.isEmpty?null:_runNow,icon:const Icon(Icons.send_rounded),label:const Text('إرسال الآن'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:_edit,icon:const Icon(Icons.tune_rounded),label:const Text('الإعدادات')))]),const SizedBox(height:18),Row(children:[Text('مجموعة الرسائل',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const Spacer(),FilledButton.tonalIcon(onPressed:_addMessage,icon:const Icon(Icons.add_rounded),label:const Text('إضافة'))]),const SizedBox(height:8),if(c.messages.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('لا توجد رسائل. أضف رسالة قبل تشغيل الجدول.')))else...c.messages.map((m)=>Card(child:ListTile(leading:CircleAvatar(child:Text('${m.sortOrder+1}')),title:Text(m.content.summary,maxLines:3,overflow:TextOverflow.ellipsis),subtitle:Text('أُرسلت ${m.timesSent} مرة'),trailing:IconButton(onPressed:()=>_deleteMessage(m.id),icon:const Icon(Icons.delete_outline_rounded))))),if(c.targetMode=='selected')...[const SizedBox(height:18),Text('المجموعات المحددة',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),...c.targets.map((t)=>ListTile(dense:true,leading:const Icon(Icons.groups_rounded),title:Text(t.groupName),subtitle:Text(t.status)))],const SizedBox(height:24),OutlinedButton.icon(onPressed:_deleteCampaign,icon:const Icon(Icons.delete_outline_rounded),label:const Text('حذف الجدول'))]));}
  Widget _info(String l,String v)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(children:[Expanded(child:Text(l)),Text(v,style:const TextStyle(fontWeight:FontWeight.bold))]));
  Future<void> _runNow()async{try{final d=await widget.controller.api.runScheduledNow(widget.campaignId);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تم وضع الإرسال #${d.id} في الطابور.')));await _load();}catch(e){_msg('تعذر الإرسال: $e');}}
  Future<void> _edit()async{final changed=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>ScheduledWizardPage(controller:widget.controller,campaign:_campaign)));if(changed==true)await _load();}
  Future<void> _addMessage()async{final content=await Navigator.push<ApiMessageContent>(context,MaterialPageRoute(builder:(_)=>_ContentDraftPage(controller:widget.controller)));if(content==null||content.isEmpty)return;await widget.controller.api.addScheduledMessage(widget.campaignId,content);await _load();}
  Future<void> _deleteMessage(int id)async{await widget.controller.api.deleteScheduledMessage(widget.campaignId,id);await _load();}
  Future<void> _deleteCampaign()async{final ok=await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:const Text('حذف الجدول؟'),content:const Text('سيتم حذف الجدول ورسائله المحفوظة.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('حذف'))]));if(ok!=true)return;await widget.controller.api.deleteScheduledCampaign(widget.campaignId);if(mounted)Navigator.pop(context,true);}void _msg(String t){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));}
}
class _ContentDraftPage extends StatefulWidget{const _ContentDraftPage({required this.controller});final AppController controller;@override State<_ContentDraftPage> createState()=>_ContentDraftPageState();}
class _ContentDraftPageState extends State<_ContentDraftPage>{ApiMessageContent _content=const ApiMessageContent(components:[]);@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('إضافة رسالة للجدول')),body:ListView(padding:const EdgeInsets.all(16),children:[ContentComposer(controller:widget.controller,value:_content,onChanged:(v)=>setState(()=>_content=v)),const SizedBox(height:20),FilledButton.icon(onPressed:_content.isEmpty?null:()=>Navigator.pop(context,_content),icon:const Icon(Icons.check_rounded),label:const Text('اعتماد المحتوى'))]));}
String _hoursText(int s){final h=s/3600;return h==h.roundToDouble()?h.toInt().toString():h.toStringAsFixed(2);}String _intervalLabel(int s){if(s<=0)return'—';if(s%86400==0)return'كل ${s~/86400} يوم';if(s%3600==0)return'كل ${s~/3600} ساعة';if(s%60==0)return'كل ${s~/60} دقيقة';return'كل $s ثانية';}String _selectionLabel(String m)=>switch(m){'shuffle'=>'عشوائي بدون تكرار','random'=>'عشوائي بالكامل','ordered'=>'بالترتيب',_=>m};String _date(int? ms){if(ms==null||ms<=0)return'—';final d=DateTime.fromMillisecondsSinceEpoch(ms).toLocal();String t(int v)=>v.toString().padLeft(2,'0');return'${d.year}-${t(d.month)}-${t(d.day)} ${t(d.hour)}:${t(d.minute)}';}
