import 'package:flutter/material.dart';
import '../../core/app_controller.dart';
import '../../core/models.dart';
import '../messaging/content_composer.dart';
import '../messaging/group_selector.dart';

class CommandsPage extends StatefulWidget{const CommandsPage({super.key,required this.controller});final AppController controller;@override State<CommandsPage> createState()=>_CommandsPageState();}
class _CommandsPageState extends State<CommandsPage>{
  final _search=TextEditingController();@override void dispose(){_search.dispose();super.dispose();}
  @override Widget build(BuildContext context){final q=_search.text.trim().toLowerCase();final items=widget.controller.commands.where((c)=>q.isEmpty||c.title.toLowerCase().contains(q)||c.triggers.any((t)=>t.text.toLowerCase().contains(q))).toList();return Scaffold(backgroundColor:Colors.transparent,appBar:AppBar(title:const Text('الردود'),backgroundColor:Colors.transparent,actions:[IconButton(onPressed:widget.controller.refreshCommands,icon:const Icon(Icons.refresh_rounded))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_open(),icon:const Icon(Icons.add_rounded),label:const Text('إضافة رد')),body:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,4,16,12),child:TextField(controller:_search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search_rounded),hintText:'بحث في الردود...'))),Expanded(child:RefreshIndicator(onRefresh:widget.controller.refreshCommands,child:items.isEmpty?ListView(children:const[SizedBox(height:140),Center(child:Text('لا توجد ردود مطابقة'))]):ListView.separated(padding:const EdgeInsets.fromLTRB(16,0,16,90),itemCount:items.length,separatorBuilder:(_,_)=>const SizedBox(height:10),itemBuilder:(context,index){final c=items[index];return Card(child:ListTile(onTap:()=>_open(c),leading:CircleAvatar(child:Icon(c.enabled?Icons.bolt_rounded:Icons.pause_rounded)),title:Text(c.title,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${c.scopeMode=='all'?'كل المجموعات':'${c.groupIds.length} مجموعة'}\n${c.responseContent.summary}',maxLines:3,overflow:TextOverflow.ellipsis),trailing:Switch(value:c.enabled,onChanged:(v)async{await widget.controller.api.updateCommand(c.id,{'enabled':v});await widget.controller.refreshCommands();})));})))]));}
  Future<void> _open([ApiCommand? c])async{final changed=await Navigator.of(context).push<bool>(MaterialPageRoute(builder:(_)=>CommandEditorPage(controller:widget.controller,command:c)));if(changed==true)await widget.controller.refreshCommands();}
}

class CommandEditorPage extends StatefulWidget{const CommandEditorPage({super.key,required this.controller,this.command});final AppController controller;final ApiCommand? command;@override State<CommandEditorPage> createState()=>_CommandEditorPageState();}
class _CommandEditorPageState extends State<CommandEditorPage>{
  late final TextEditingController _trigger;late int _cooldown;late bool _enabled;late String _scopeMode;late Set<int> _groupIds;late ApiMessageContent _content;int _step=0;bool _saving=false;bool get editing=>widget.command!=null;
  @override void initState(){super.initState();final c=widget.command;_trigger=TextEditingController(text:c?.title??'');_cooldown=c?.cooldownSeconds??3;_enabled=c?.enabled??true;_scopeMode=c?.scopeMode??'all';_groupIds={...?c?.groupIds};_content=c?.responseContent??const ApiMessageContent(components:[]);}
  @override void dispose(){_trigger.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(editing?'تعديل الرد':'إضافة رد جديد')),body:Stepper(currentStep:_step,onStepTapped:(v)=>setState(()=>_step=v),onStepContinue:_saving?null:_continue,onStepCancel:_saving?null:(){if(_step>0)setState(()=>_step--);},controlsBuilder:(context,d)=>Padding(padding:const EdgeInsets.only(top:18),child:Row(children:[FilledButton.icon(onPressed:d.onStepContinue,icon:Icon(_step==3?Icons.save_rounded:Icons.arrow_forward_rounded),label:Text(_step==3?(editing?'حفظ التعديلات':'إنشاء الرد'):'التالي')),if(_step>0)...[const SizedBox(width:8),TextButton(onPressed:d.onStepCancel,child:const Text('السابق'))]])),steps:[
    Step(title:const Text('1. الأمر والإعدادات'),isActive:_step>=0,content:Column(children:[TextField(controller:_trigger,enabled:!editing,maxLength:200,decoration:InputDecoration(labelText:'الكلمة/الأمر الدقيق',helperText:editing?'الأمر الأساسي لا يتغير؛ استخدم الأسماء البديلة لإضافة صيغة أخرى.':'الرد يعمل عند تطابق الرسالة مع هذا الأمر.')),const SizedBox(height:10),Row(children:[Expanded(child:Text('فترة الانتظار: $_cooldown ثانية')),SizedBox(width:180,child:Slider(value:_cooldown.toDouble(),min:0,max:60,divisions:60,onChanged:(v)=>setState(()=>_cooldown=v.round())))]),if(editing)SwitchListTile(contentPadding:EdgeInsets.zero,value:_enabled,title:const Text('الرد مفعّل'),onChanged:(v)=>setState(()=>_enabled=v))])),
    Step(title:const Text('2. المجموعات'),isActive:_step>=1,content:GroupSelector(groups:widget.controller.groups,mode:_scopeMode,selectedIds:_groupIds,onModeChanged:(v)=>setState((){_scopeMode=v;if(v=='all')_groupIds.clear();}),onSelectionChanged:(v)=>setState(()=>_groupIds=v),allLabel:'كل المجموعات')),
    Step(title:const Text('3. محتوى الرد'),isActive:_step>=2,content:ContentComposer(controller:widget.controller,value:_content,onChanged:(v)=>_content=v,title:'محتوى الرد بالترتيب')),
    Step(title:const Text('4. المراجعة والحفظ'),isActive:_step>=3,content:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_review('الأمر',_trigger.text.trim()),_review('النطاق',_scopeMode=='all'?'جميع المجموعات المعتمدة':'${_groupIds.length} مجموعة محددة'),_review('Cooldown','$_cooldown ثانية'),const SizedBox(height:12),Text('المحتوى',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),Card(child:Padding(padding:const EdgeInsets.all(14),child:Text(_content.summary))),if(editing)...[const SizedBox(height:16),_AliasesEditor(controller:widget.controller,command:widget.command!),const SizedBox(height:12),OutlinedButton.icon(onPressed:_delete,icon:const Icon(Icons.delete_outline_rounded),label:const Text('حذف الرد نهائيًا'))],if(_saving)const Padding(padding:EdgeInsets.only(top:16),child:LinearProgressIndicator())]))
  ]));
  Widget _review(String t,String v)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(t),trailing:Flexible(child:Text(v,textAlign:TextAlign.end,style:const TextStyle(fontWeight:FontWeight.bold))));
  Future<void> _continue()async{if(_step==0&&_trigger.text.trim().isEmpty)return _message('اكتب الأمر أولًا.');if(_step==1&&_scopeMode=='selected'&&_groupIds.isEmpty)return _message('اختر مجموعة واحدة على الأقل.');if(_step==2&&_content.isEmpty)return _message('أضف نصًا أو وسائط للرد.');if(_step<3){setState(()=>_step++);return;}await _save();}
  Future<void> _save()async{setState(()=>_saving=true);try{if(editing){await widget.controller.api.updateCommand(widget.command!.id,{'responseContent':_content.toJson(),'scopeMode':_scopeMode,'groupIds':_scopeMode=='all'?<int>[]:_groupIds.toList(),'cooldownSeconds':_cooldown,'enabled':_enabled});}else{await widget.controller.api.createCommand(trigger:_trigger.text.trim(),responseContent:_content,scopeMode:_scopeMode,groupIds:_groupIds.toList(),cooldownSeconds:_cooldown);}if(mounted)Navigator.pop(context,true);}catch(e){_message('تعذر الحفظ: $e');}finally{if(mounted)setState(()=>_saving=false);}}
  Future<void> _delete()async{final ok=await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:const Text('حذف الرد؟'),content:const Text('سيتم حذف الرد نهائيًا.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('حذف'))]));if(ok!=true)return;await widget.controller.api.deleteCommand(widget.command!.id);if(mounted)Navigator.pop(context,true);}
  void _message(String t){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));}
}
class _AliasesEditor extends StatefulWidget{const _AliasesEditor({required this.controller,required this.command});final AppController controller;final ApiCommand command;@override State<_AliasesEditor> createState()=>_AliasesEditorState();}
class _AliasesEditorState extends State<_AliasesEditor>{final _alias=TextEditingController();late ApiCommand _command;@override void initState(){super.initState();_command=widget.command;}@override void dispose(){_alias.dispose();super.dispose();}@override Widget build(BuildContext context)=>ExpansionTile(tilePadding:EdgeInsets.zero,title:const Text('الأسماء البديلة'),subtitle:Text('${_command.triggers.length-1} اسم بديل'),children:[Wrap(spacing:8,runSpacing:8,children:_command.triggers.map((t)=>InputChip(label:Text(t.text),onDeleted:t.primary?null:()=>_remove(t))).toList()),const SizedBox(height:10),Row(children:[Expanded(child:TextField(controller:_alias,decoration:const InputDecoration(labelText:'اسم بديل جديد'))),const SizedBox(width:8),IconButton.filled(onPressed:_add,icon:const Icon(Icons.add_rounded))])]);Future<void> _add()async{final v=_alias.text.trim();if(v.isEmpty)return;_command=await widget.controller.api.addAlias(_command.id,v);_alias.clear();if(mounted)setState((){});}Future<void> _remove(ApiTrigger t)async{_command=await widget.controller.api.removeAlias(_command.id,t.id);if(mounted)setState((){});}}
